### PR TITLE
jQuery.noop returns undefined, not a function

### PR DESCRIPTION
**Pull request by tdelmas**
See https://api.jquery.com/jquery.noop/ and https://github.com/jquery/jquery/blob/master/src/core.js#L207

---
This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1790)

### CODE REVIEW

**Comment by Dominator008** [comment]
@tdelmas Looks good, thanks!

**Comment by MatrixFrog** [comment]
Presumably they meant to write `@type {function()}` not `@return {function()}`. Good catch, will bring this in soon.

**Comment by tdelmas** [comment]
I catch it because I had something like `var f = $.noop; var res = f(); if ( res === undefined ) {...}` and a warning saying that my `res === undefined` is always `false` because `res` is a function.

I think the `@return {undefined}` annotation is missing for angular.noop too. Should I open a Issue/Pull request ?

**Comment by Dominator008** [comment]
@tdelmas Yes, feel free to open another pull request for `angular.noop`.

**Pull request closed without merging**
