### PR TITLE
Remove Resource.as() for backward compatibility with ant 1.7.1

### PR DESCRIPTION
**Pull request by rcchan**

### CODE REVIEW

**Comment by MatrixFrog** [comment]
lgtm. waiting to see if the googlebot will do its magic.

**Comment by rcchan** [comment]
Googlebot has not merged yet. Does it need a cla:yes tag?

**Comment by MatrixFrog** [comment]
googlebot doesn't auto-merge, it just adds the cla:yes tag. No idea why it didn't work. Anyway, I don't see you on the list. Did you sign it using a different Github username?

**Comment by rcchan** [comment]
I think I signed it with my email address (same one as on the commits)

**Comment by MatrixFrog** [comment]
Got it. Thanks!

**Pull request merged**
