### PR TITLE
Remove unused field "acceptTypeSyntax" from CompilerOptions

### PR DESCRIPTION
**Pull request by Dominator008**

### CODE REVIEW

**Comment by Dominator008** [comment]
Not sure if there's internal usage of this, but I guess there's none.

**Comment by mprobst** [comment]
@Dominator008 yeah, I'm not sure where that came from, but I think ECMASCRIPT6_TYPED is now used for that purpose.

LGTM.

**Comment by MatrixFrog** [comment]
Looks like we are actually using it in some code that is MOE-stripped out :(

**Comment by mprobst** [comment]
Making open "easy" :-(

Maybe it's possible to recover in the sync CL?

**Pull request merged**
