### PR TITLE
Update jquery-3.3.js jQuery.noConflict() type

### PR DESCRIPTION
**Pull request by ComputerJy**
Having return type Object for the noConflict function causes Closure compiler to warn about object expressions not being callable.

### CODE REVIEW

**Comment by ComputerJy** [comment]
I signed it

**Comment by brad4d** [comment]
Internal issue http://b/129955426 created.

**Comment by brad4d** [comment]
Imported and sent for internal review and approval.

**Comment by brad4d** [comment]
@ComputerJy I've pushed back to your branch a simplified form of your change.
Could you confirm that it works for your use case before I submit it on my side?

Thanks.

**Comment by ComputerJy** [comment]
> @ComputerJy I've pushed back to your branch a simplified form of your change.
> Could you confirm that it works for your use case before I submit it on my side?
> 
> Thanks.

This works just fine. Thanks

**Comment by brad4d** [comment]
I'm submitting this change internally. It should be included in tomorrow's push to GitHub.

**Pull request closed without merging**
