### PR TITLE
Changed the GWT ResourceLoader to include most of the built-in externs.

### PR DESCRIPTION
**Pull request by Dominator008**
Modify GwtRunner to load the built-in externs and change the default
languageIn to ES6.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1641)

### CODE REVIEW

**Comment by Dominator008** [comment]
This requires internal BUILD change.

**Comment by blickly** [comment]
Just letting you know, that we have a slightly different approach to GWT resources like these internally that @shicks is working on that will conflict with this PR (but I think will be easier to support for both internal and external use)

**Comment by Dominator008** [comment]
@blickly OK sounds good!

**Comment by blickly** [comment]
Closing this, as we're planning on including these resources in a different way, as started in https://github.com/google/closure-compiler/commit/59383e4bebcee4bc5ea48ea5d4a0bc94c0f03621

**Pull request closed without merging**
