### PR TITLE
Make processBinaryExpression() iterative in IRFactory

### LINKED ISSUE #1661: StackOverflowError occurs when thousands of strings are concatenated in a single expression
Here's the repeating portion of the stack trace:

```
$ java -jar compiler.jar test.js
java.lang.StackOverflowError
	at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931) 
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:734)
	at com.google.javascript.jscomp.parsing.IRFactory.access$300(IRFactory.java:163)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression(IRFactory.java:1322)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2517)
	at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931)
```

test.js is attached. Note it's a concatenation of 2,000 strings in a single expression.

There are two workarounds for this issue that I have found:

1. Break the string concatenation up into multiple statements
2. Increase JVM stack size, e.g. -Xss8M

[test.js.zip](https://github.com/google/closure-compiler/files/174985/test.js.zip)

### PR DESCRIPTION
**Pull request by Dominator008**
This prevents the StackOverFlowError when parsing a huge binary
expression.

Fixes #1661.

---

This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1756)

### CODE REVIEW

**Comment by Dominator008** [comment]
cc @concavelenz

**Comment by blickly** [comment]
John has a very similar change under review

**Comment by Dominator008** [comment]
@blickly OK sounds good.

**Comment by blickly** [comment]
See:
https://github.com/google/closure-compiler/commit/069e6378f8ba41372c9a1a38d4f4ebbbb4328fe1

Leaving this open in case you decide to work on the JSDoc case, but I'd guess it's much lower priority.

**Comment by concavelenz** [comment]
Reopen if we decide we need this.

**Comment by shivekkhurana** [comment]
Hi @concavelenz,
This PR is from 2017 and the issue #1661 is many years old too. But I get this StackOverflow error with `@blueprintjs/icons` version `3.18.1` and above. The compiler is unable to parse a file that contains a 10k character long line ([🗄️ file source](https://unpkg.com/browse/@blueprintjs/icons@3.18.1/lib/cjs/generated/iconContents.js)).

**Error Stack Trace**
```
RuntimeException: Exception parsing "/Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/generated/iconContents.js"
	com.google.javascript.jscomp.parsing.ParserRunner.parse (ParserRunner.java:155)
	com.google.javascript.jscomp.JsAst.parse (JsAst.java:152)
	com.google.javascript.jscomp.JsAst.getAstRoot (JsAst.java:55)
...
Caused by:
StackOverflowError:
	com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc (IRFactory.java:678)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:829)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpressionHelper (IRFactory.java:1840)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1816)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:3275)
```

- Do you think my issue is related to the one being discussed on this thread?
- If it is, does it makes sense to make a change upstream? Or is it better to contact the authors of Blueprint?

Thanks

**Pull request closed without merging**
