### PR TITLE
Added to Element.insertAdjacent* to externs

### PR DESCRIPTION
**Pull request by jonathan-rosa**
This is a pull request for (https://github.com/google/closure-compiler/issues/3516)

Adds support for `Element.insertAdjacentElement`, `Element.insertAdjacentHTML`, and `Element.insertAdjacentText`. These methods have good browser support have been added to `w3c_dom4.js`.

### CODE REVIEW

**Comment by DeltaFlush** [comment]
Are we looking to merge this?

**Comment by lauraharker** [comment]
Please address the failures in the Travis build:

```
Tests run: 181, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 10.704 sec <<< FAILURE! - in com.google.javascript.jscomp.CommandLineRunnerTest
testForOfTypecheck(com.google.javascript.jscomp.CommandLineRunnerTest)  Time elapsed: 0.71 sec  <<< FAILURE!
com.google.common.truth.ComparisonFailureWithFacts: 
Expected exactly one warning or error 
Errors: 
JSC_HIDDEN_SUPERCLASS_PROPERTY_MISMATCH. mismatch of the insertAdjacentHTML property type and the type of the property it overrides from superclass Node
original: function(this:Node, string, (TrustedHTML|string)): undefined
override: function(this:Element, string, string): undefined at externs.zip//w3c_dom4.js line 268 : 0
JSC_INEXISTENT_PROPERTY. Property meow never defined on Dog at input0 line 8 : 6
Warnings: 
expected: 1
but was : 2
	at com.google.javascript.jscomp.CommandLineRunnerTest.test(CommandLineRunnerTest.java:2783)
	at com.google.javascript.jscomp.CommandLineRunnerTest.test(CommandLineRunnerTest.java:2764)
	at com.google.javascript.jscomp.CommandLineRunnerTest.testForOfTypecheck(CommandLineRunnerTest.java:168)
```

(https://www.chromestatus.com/feature/5650088592408576 for more context on TrustedHTML. I believe `Element.protoype.insertAdjacentHTML` needs to accept a `TrustedHTML` but I'm not super familiar with Trusted Types)

**Comment by jonathan-rosa** [comment]
@googlebot I fixed it.

**Comment by rishipal** [comment]
WIP- Fixing internal test failures.

**Comment by rishipal** [comment]
Update: WIP; fixing some more of the pending internal test failures.

**Comment by rishipal** [comment]
Out of the 3 properties being added to Element in the browser externs, one property (`insertAdjacentHTML`) has multiple declarations across internal google3 code, causing ~hundreds of redeclaration errors. 

I will proceed to merge the changes for the other two properties `Element.insertAdjacentElement` and `Element.insertAdjacentText`.

**Pull request merged**
