### PR TITLE
Re-add the setClosureEntryPoints method

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
setClosureEntryPoints is deprecated, but used internally at Google. This re-adds the method to AbstractCommandLineRunner to aid in migration to the new setEntryPoints signature.

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
@blickly I just noticed that the list is Immutable - so this won't quite work as-is.

**Comment by ChadKillingsworth** [comment]
Ok that should do it.

**Comment by blickly** [comment]
Thanks for the quick response!
I just noticed that we also have usages of the old createDependencyOptions, so now I'm thinking it might be easier to just have a couple helpers here:
  List<String> -> List<ModuleIdentifier>
and
  (boolean, boolean) -> DependencyMode
and then I can fix up the callers using those in our internal code.
I'm pretty sure this will be cleaner than trying to support all of the old API usages that we have internally.

**Comment by ChadKillingsworth** [comment]
@blickly I think this is what you had in mind. Let me know if you want something different.

**Comment by blickly** [comment]
Great, perfect! Thanks Chad

**Pull request closed without merging**
