### PR TITLE
Add missing extern for Symbol.split

### PR DESCRIPTION
**Pull request by realityforge**

### CODE REVIEW

**Comment by realityforge** [comment]
Any chance that this can be looked at?

**Comment by brad4d** [comment]
I've just reviewed and approved this internally.

**Comment by rishipal** [comment]
Adding this extern causes code size regression in internal tests. 

It's possible that disambiguation is conflating the Symbol's split property with another split property. Adding a misspelt `Symbol.splitt` extern instead does not cause the size regression.

I will need to investigate this more. Is this PR blocking?

**Comment by realityforge** [comment]
Not blocking for us as we have added a local extern but it would great if it eventually landed ;)

**Comment by realityforge** [comment]
Closing this to get it off my plate as it seems unlikely to be merged

**Pull request closed without merging**
