### PR TITLE
Debian build files, required for .deb generation

### PR DESCRIPTION
**Pull request by cdp1337**
https://groups.google.com/forum/#!topic/closure-compiler-discuss/xZOf5QfAi3k

### CODE REVIEW

**Comment by cdp1337** [comment]
I signed it!

**Comment by blickly** [comment]
Cool, thanks for the contribution!
Can you check that you included your github username in the CLA?

**Comment by cdp1337** [comment]
The CLA just requests a google group address, so I'm at a loss of how to link a github username to a google group.  The corporate email is registered as a member in that group though, as is my personal email.

**Comment by blickly** [comment]
OK, thanks! I must admit I don't fully understand the bot's failure modes. Importing now...

**Pull request closed without merging**
