### PR TITLE
update HTML5 externs to have non-null types

### PR DESCRIPTION
**Pull request by myphysicslab**
Update definitions in HTML5 externs to specify non-null types (adding ! exclamation mark) where appropriate.   Only return and property types have been changed. I've done some cursory internet research on these changes.

Add the ? nullable type for some return and property types in cases where the spec is clear about that.

This addresses issues #860 and #2425.

### CODE REVIEW

**Comment by brad4d** [comment]
The PR looks good to me.
I've imported it and will do a 'test all the things' run on it.

**Comment by brad4d** [comment]
Overlooked change of `setLineDash()` parameter to non-nullable.
It broke 4000+ tests. :)
Nothing else was a problem, though, so I'm trying to submit this internally with the `setLineDash()` parameter restored to nullable.

**Comment by brad4d** [comment]
Submitted internally.
Should get pushed to github tomorrow.

**Comment by myphysicslab** [comment]
Great, sorry I missed undoing that change to `setLineDash` parameter.

**Pull request closed without merging**
