### PR TITLE
Remove live connect externs and navigator global

### PR DESCRIPTION
**Pull request by realityforge**
This needs to be applied at the same time as google/elemental#115

### CODE REVIEW

**Comment by blickly** [comment]
Created internal issue http://b/131364800

**Comment by lauraharker** [comment]
There are a few internal projects referencing `java` (although none of the other deleted externs are used). I'll see if we can remove those.

**Comment by realityforge** [comment]
Thanks for looking into it

**Comment by lauraharker** [comment]
I've sent this for internal review.

**Comment by realityforge** [comment]
Thanks!

**Pull request closed without merging**
