### PR TITLE
Fix glob on Windows and fix regression

### LINKED ISSUE #1407: Cannot use globs when running the compiler.
Since 62ca536... I am no longer able to use globs for files when running the compiler:

Running this command used to work before that change:
```
java -jar ../../compiler/compiler.jar \
--flagfile=options/compile.ini \
--define "goog.json.USE_NATIVE_JSON=true" --define "goog.ui.Component.ALLOW_DETACHED_DECORATION=true" --define "goog.NATIVE_ARRAY_PROTOTYPES=true" --define "goog.array.ASSUME_NATIVE_FUNCTIONS=true" --define "goog.Promise.UNHANDLED_REJECTION_DELAY=-1"  --define "app.settings.RUN_AS_USER=false" --externs=../externs/material.js --generate_exports --export_local_property_definitions --language_in=ECMASCRIPT6 --language_out=ES3 --use_types_for_optimization --output_wrapper="(function(){%output%})();" \
--only_closure_dependencies \
--closure_entry_point=app \
--manage_closure_dependencies true \
--output_manifest build/app.filelist.txt \
--js_output_file /tmp/closure_compiler_build \
--js="js/**.js" --js="tpl/en/**.js" --js="../../templates/soyutils_usegoog.js" --js="../../library/closure/goog/**.js" --js="../../library/third_party/closure/goog/mochikit/async/deferred.js" --js="../../library/third_party/closure/goog/mochikit/async/deferredlist.js" --js="../pstj/animation/**.js" --js="../pstj/app/**.js" --js="../pstj/autogenerated/**.js" --js="../pstj/cast/**.js" --js="../pstj/color/**.js" --js="../pstj/config/**.js" --js="../pstj/control/**.js" --js="../pstj/date/**.js" --js="../pstj/debug/**.js" --js="../pstj/ds/**.js" --js="../pstj/element/**.js" --js="../pstj/error/**.js" --js="../pstj/fx/**.js" --js="../pstj/graphics/**.js" --js="../pstj/material/**.js" --js="../pstj/math/**.js" --js="../pstj/mvc/**.js" --js="../pstj/ng/**.js" --js="../pstj/object/**.js" --js="../pstj/options/**.js" --js="../pstj/resource/**.js" --js="../pstj/sourcegen/**.js" --js="../pstj/storage/**.js" --js="../pstj/style/**.js" --js="../pstj/themes/**.js" --js="../pstj/ui/**.js" --js="../smjs/ds/**.js" --js="../smjs/element/**.js" --js="../smjs/persistence/**.js" --js="../smjs/player/**.js" --js="../smjs/remotecontrol/**.js" --js="../smjs/transport/**.js" --js="../smjs/tv/**.js" --js="../smjs/widgets/**.js" --js="!**_test.js"
```

Now (after the mentioned change) it gives this:
```
ERROR - Cannot read: !**_test.js

ERROR - Cannot read: ../../library/closure/goog/**.js

ERROR - Cannot read: ../pstj/animation/**.js

ERROR - Cannot read: ../pstj/app/**.js

ERROR - Cannot read: ../pstj/autogenerated/**.js

ERROR - Cannot read: ../pstj/cast/**.js

ERROR - Cannot read: ../pstj/color/**.js

ERROR - Cannot read: ../pstj/config/**.js

ERROR - Cannot read: ../pstj/control/**.js

ERROR - Cannot read: ../pstj/date/**.js

ERROR - Cannot read: ../pstj/debug/**.js

ERROR - Cannot read: ../pstj/ds/**.js

ERROR - Cannot read: ../pstj/element/**.js

ERROR - Cannot read: ../pstj/error/**.js

ERROR - Cannot read: ../pstj/fx/**.js

ERROR - Cannot read: ../pstj/graphics/**.js

ERROR - Cannot read: ../pstj/material/**.js

ERROR - Cannot read: ../pstj/math/**.js

ERROR - Cannot read: ../pstj/mvc/**.js

ERROR - Cannot read: ../pstj/ng/**.js

ERROR - Cannot read: ../pstj/object/**.js

ERROR - Cannot read: ../pstj/options/**.js

ERROR - Cannot read: ../pstj/resource/**.js

ERROR - Cannot read: ../pstj/sourcegen/**.js

ERROR - Cannot read: ../pstj/storage/**.js

ERROR - Cannot read: ../pstj/style/**.js

ERROR - Cannot read: ../pstj/themes/**.js

ERROR - Cannot read: ../pstj/ui/**.js

ERROR - Cannot read: ../smjs/ds/**.js

ERROR - Cannot read: ../smjs/element/**.js

ERROR - Cannot read: ../smjs/persistence/**.js

ERROR - Cannot read: ../smjs/player/**.js

ERROR - Cannot read: ../smjs/remotecontrol/**.js

ERROR - Cannot read: ../smjs/transport/**.js

ERROR - Cannot read: ../smjs/tv/**.js

ERROR - Cannot read: ../smjs/widgets/**.js

ERROR - Cannot read: js/**.js

ERROR - Cannot read: tpl/en/**.js

ERROR - required entry point "app" never provided

39 error(s), 0 warning(s)
```

### LINKED ISSUE #1477: Ant tests failing on Windows
Presumably this is an Ant-specific issue since the build is shown to be passing. I checked out today's 7af4fc1fa30d000b438c0acb9c34678c0b57cf16 and ```ant clean test``` produced 4 failures in CommandLineRunnerTest, e.g.:

```
testGlobJs1	Error	expected:<[var a;var b;]> but was:<[]>

org.junit.ComparisonFailure: expected:<[var a;var b;]> but was:<[]>
at com.google.common.truth.Platform.comparisonFailure(Platform.java:133)
at com.google.common.truth.Truth$1.failComparing(Truth.java:62)
at com.google.common.truth.StringSubject.isEqualTo(StringSubject.java:64)
at com.google.javascript.jscomp.CommandLineRunnerTest.compileFiles(CommandLineRunnerTest.java:1942)
at com.google.javascript.jscomp.CommandLineRunnerTest.testGlobJs1(CommandLineRunnerTest.java:1104)
```

I believe the plan is to drop support for Ant, but didn't think this was done yet.

I tried also ```mvn test``` and it hung on CommandLineRunnerTest (?) - after several minutes with zero CPU, I killed it. Running the test individually from Eclipse shows it is waiting for stdin in CommandLineRunner:682

Am I missing something, or is this a genuine issue? I'm trying to rebase a PR branch and can't tell if it's got a problem.

### PR DESCRIPTION
**Pull request by Dominator008**
Fixes #1407.
Fixes #1477.

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
I can test this tonight, but I don't have a windows build environment at the office.

**Comment by Dominator008** [comment]
@ChadKillingsworth This is passing on my Windows environment.

**Comment by ChadKillingsworth** [comment]
Yeah I just meant if we wanted someone else to try it out - since Travis can't build on Windows.

**Comment by Dominator008** [comment]
@supersteves Can you help verifying this? Thanks!

**Comment by ChadKillingsworth** [comment]
@Dominator008 Did you see the comment by @joeltine on #1407? Does that pattern work with this change?

**Comment by Dominator008** [comment]
@ChadKillingsworth No it doesn't seem so :(

**Comment by Dominator008** [comment]
@ChadKillingsworth OK the regression should be fixed now.

**Comment by supersteves** [comment]
Fix verified :+1:
(strange how Ant failed but Mvn hung, though - but both working now)

**Comment by Dominator008** [comment]
Thanks @supersteves !

**Comment by dimvar** [comment]
@Dominator008 can you add a unit test for the `--js='!**\./node_modules**.js'` pattern?

**Comment by dimvar** [comment]
Other than that lgtm

**Comment by Dominator008** [comment]
@dimvar The unit test for `--js='!**\./foo**.js'` requires creating a temporary directory under the current working directory (see `testGlobJs5`). This works on my machine, but I'm not sure if it will work internally since we need to have write permission on the current working directory.

**Comment by dimvar** [comment]
OK sounds good. LGTM then. I'll look to see if I can add a unit test internally after this lands. I'll merge this once Travis is done.

**Comment by dimvar** [comment]
@Dominator008 looks like the travis build failed. Can you look into it so we can merge the PR?

**Comment by Dominator008** [comment]
@dimvar The Travis build failed for other reasons and I fixed them in #1486. I've rebased this on top of master. Let's see if this one succeeds :)

**Comment by dimvar** [comment]
Thanks! Feel free to merge this once Travis is done.

**Pull request merged**
