### PR TITLE
Add mockDate function to jasmine clock extern

### PR DESCRIPTION
**Pull request by calebegg**

### CODE REVIEW

**Comment by calebegg** [comment]
I am covered by the Google Corporate CLA (I am a Google employee).

**Comment by MatrixFrog** [comment]
In that case, it's preferable to send changes internally so we don't have to re-LGTM them when MOE pulls them in.

But if you do send changes internally, I've found that if the commit has your @google.com address the googlebot is happy.

**Comment by MatrixFrog** [comment]
Er, I meant, if you do send changes _externally_ of course.

**Comment by calebegg** [comment]
Sent. Thanks for the heads up.

**Pull request closed without merging**
