### PR TITLE
Specify the return type of some console functions.

### PR DESCRIPTION
**Pull request by realityforge**
This aligns the types with the whatwg spec and with contrib/nodejs/globals.js

### CODE REVIEW

**Comment by realityforge** [comment]
Note this has been extracted from #3268 to simplify merging

**Comment by tjgq** [comment]
Created Google internal issue b/128868025. Imported for internal review and testing.

**Comment by ChadKillingsworth** [comment]
If you specify the return type, you need to specify the arguments as well. An extern with no type information is assumed to return any type and take any number of arguments of any type.

**Comment by realityforge** [comment]
@ChadKillingsworth As far as I can tell, neither of these methods have any parameters according to either the spec (See [1] & [2]) or according to MDN (See [3] & [4]).

Or am I missing something? 

[1] https://console.spec.whatwg.org/#clear
[2] https://console.spec.whatwg.org/#groupend
[3] https://developer.mozilla.org/en-US/docs/Web/API/Console/clear
[4] https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd

**Comment by realityforge** [comment]
👍

**Pull request closed without merging**
