### PR TITLE
Stripe.js v2 extern

### PR DESCRIPTION
**Pull request by BradMclain**
Validated working with 25-02-2016 issue of the library

---
This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1788)

### CODE REVIEW

**Comment by Dominator008** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[contrib/externs/stripe-2.0.js, line 2 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXD4jKGXH9aidOHNAL:-KHXD4jKGXH9aidOHNAM:492283013) ([raw file](https://github.com/google/closure-compiler/blob/18390c2d2f955127bbcebb8393b125069b426d0a/contrib/externs/stripe-2.0.js#L2)):*
> ```JavaScript
> /**
>  * Copyright 2016 Anomaly Software Pty Ltd.
> ```

This needs to be "Copyright 2016 The Closure Compiler Authors.".

---

*[contrib/externs/stripe-2.0.js, line 34 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXDVSp9VfrQNM86nH0:-KHXDVSp9VfrQNM86nH1:1841215307) ([raw file](https://github.com/google/closure-compiler/blob/18390c2d2f955127bbcebb8393b125069b426d0a/contrib/externs/stripe-2.0.js#L34)):*
> ```JavaScript
> 
> /**
>  * @param {string} t
> ```

Can we use more descriptive parameter names instead of `t`, `r` and `n`? 

---

*[contrib/externs/stripe-2.0.js, line 36 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXDEM2bKTZEupDrQKQ:-KHXDEM2bKTZEupDrQKR:1572096425) ([raw file](https://github.com/google/closure-compiler/blob/18390c2d2f955127bbcebb8393b125069b426d0a/contrib/externs/stripe-2.0.js#L36)):*
> ```JavaScript
>  * @param {string} t
>  */
> Stripe.setPublishableKey = function(t) { };
> ```

Remove the extra space between `{` and `}`, so make it `Stripe.setPublishableKey = function(t) {};`. The same applies to the stubs below.

---

*[contrib/externs/stripe-2.0.js, line 69 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXDMl6ROjxTXAN-peK:-KHXDMl6ROjxTXAN-peL:1873422051) ([raw file](https://github.com/google/closure-compiler/blob/18390c2d2f955127bbcebb8393b125069b426d0a/contrib/externs/stripe-2.0.js#L69)):*
> ```JavaScript
>  * @param {Function} r
>  */
> Stripe.bankAccount.createToken = function(t,r) {};
> ```

Missing a space after the comma, so make it `Stripe.bankAccount.createToken = function(t, r) {};`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1788)*

**Comment by BradMclain** [comment]
I have already signed a CLA for this GitHub account. What else do I need to do to make the bot happy?

**Comment by MatrixFrog** [comment]
Make sure the author email on every commit matches the email address associated with your gh account.

**Comment by Dominator008** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/externs/stripe-2.0.js, line 110 \[r5\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXN-9N_0fNv6bneBPG:-KHXN-9N_0fNv6bneBPH:-316356213) ([raw file](https://github.com/google/closure-compiler/blob/5e242c9d88038c97892ba676ce0317b6e5dbe4f9/contrib/externs/stripe-2.0.js#L110)):*
> ```JavaScript
>  * @param {string} receiverId
>  */
> Stripe.bitcoinReceiver.cancelReceiverPoll = function(receiverId) {};
> ```

Need a newline at the end of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1788)*

**Comment by Dominator008** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/externs/stripe-2.0.js, line 45 \[r6\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHXQTAusN_fT9yvNZ3A:-KHXQTAusN_fT9yvNZ3B:189865762) ([raw file](https://github.com/google/closure-compiler/blob/0bc1fb91355a5b3e707c7a0357dce654239d0ddc/contrib/externs/stripe-2.0.js#L45)):*
> ```JavaScript
> 
> /**
>  * @param {Object} cardDetails
> ```

Optional: Instead of typing these as general `Object` and `Function`, have you considered restricting them to more concrete types according to the Stripe API? Doing so will improve type checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1788)*

**Comment by BradMclain** [comment]
I could improve on these definitions but might not get to it immediately.

Is there some examples to follow for both object and function parameters you can refer me to?

**Comment by Dominator008** [comment]
@BradMclain Yes. Take a look at "Record Type" and "Function Type" in https://developers.google.com/closure/compiler/docs/js-for-compiler#types.

**Comment by BradMclain** [comment]
Made a start on this, just checking if this is what you are after?

**Comment by Dominator008** [comment]
@BradMclain Yes this is what I was suggesting. The `Object` types can be record types with required and optional fields.

**Comment by Dominator008** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contrib/externs/stripe-2.0.js, line 102 \[r8\]](https://reviewable.io:443/reviews/google/closure-compiler/1788#-KHbUsuESdhNaqPHgX_L:-KHbUsuFM2y2P5D8lT8e:-2130868915) ([raw file](https://github.com/google/closure-compiler/blob/76a8418df74f570b1d56d8146b8d56cf84cfe1f6/contrib/externs/stripe-2.0.js#L102)):*
> ```JavaScript
> /**
>  * @param {StripeAccountData|Element} accountDataOrForm
>  * @param {function(string, Object)} callback
> ```

 Looking good. Can these `Object`s in the callback be defined as record too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1788)*

**Comment by BradMclain** [comment]
Sure i'll try add those when I get a chance.

**Comment by BradMclain** [comment]
How does this look?

**Pull request closed without merging**
