### PR TITLE
New pass WhitespaceWrapGoogModules in specialist "always pre-check" phase (fixes #611) [rebuilt]

### LINKED ISSUE #611: Whitespace only mode breaks goog.module
goog.module needs to be wrapped or rewritten and whitespace only mode does neither.

### PR DESCRIPTION
**Pull request by supersteves**
Replacement for PR https://github.com/google/closure-compiler/pull/1123 which fixes Git history.  See original PR for discussion including @blickly last comment:

> ... So looks like this is safe to merge even if people are relying on the two-step workflow. ...

I'd broken my previous branch by doing some merge in the past which was causing tons of conflicts when I rebased, so I started again with a clean branch from today's google/master, and cherry-picked all my non-merge commits (no conflicts or compilation errors resulted).

This constitutes exactly the same changes we were consulting on in the previous PR, but freshly applied to master. I haven't added or removed any changes.

[Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1365)

### CODE REVIEW

**Comment by Dominator008** [comment]
@supersteves Can you rebase and squash the commits?

**Comment by supersteves** [comment]
Sure, done.

**Comment by blickly** [comment]
Thanks!

**Comment by supersteves** [comment]
Freshly rebased. Change is now smaller due to @blickly's identical NodeUtil refactoring.

**Comment by fgravin** [comment]
Hi,

We are using last version 20170124 of closure compiler.
Whitespace_only module put the content oy my module at the root level of the output file, it's absolutly not managed by the moduleLoader.

```js
goog.module('fileService');
goog.module.declareLegacyNamespace();
goog.require('File');

exports.module = angular.module('fileService', []);
exports.module.service('File', File);
```
`goog.module('fileService')` is not wraped into a module Loader, `exports` then is null.

Have i missed something or the bug still here ?

**Pull request closed without merging**
