### PR TITLE
Add Maven artifact without bundled dependencies

### PR DESCRIPTION
**Pull request by michaelhixson**
Fixes https://github.com/google/closure-compiler/issues/1218.

[Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1594)

### CODE REVIEW

**Comment by michaelhixson** [comment]
I signed the CLA

**Comment by michaelhixson** [comment]
Commenting in case that triggers googlebot to check the CLA again.

**Comment by MatrixFrog** [comment]
Cool. Are the instructions in the README still correct?

**Comment by michaelhixson** [comment]
@MatrixFrog Yeah, the README's instructions still work.  When I run `mvn -DskipTests`, I end up with these files in `target/`:

* `closure-compiler-1.0-SNAPSHOT.jar` - the same as it was before: the artifact you publish now
* `closure-compiler-1.0-SNAPSHOT-shaded.jar` - I'm not sure why file is here when I build with my fork, but not when I build from master.  It's a copy of the first file.
* `closure-compiler-1.0-SNAPSHOT-sources.jar`
* `closure-compiler-gwt-1.0-SNAPSHOT.war`
* `closure-compiler-unshaded-1.0-SNAPSHOT.jar` - this is the new artifact without bundled deps
* `closure-compiler-unshaded-1.0-SNAPSHOT-sources.jar` - this is exactly the same as the other -sources jar, but I bet you would want to publish both anyway
* `original-closure-compiler-1.0-SNAPSHOT.jar`

**Comment by MatrixFrog** [comment]
Submitting this internally first since it will require BUILD changes. Thank you.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/be541be9e6be04638afc1bba0421d15c69d89533.

**Comment by michaelhixson** [comment]
Sweet.  I hope I didn't break the internal build!

And I hope you're ok with the new artifact names.  `closure-compiler-unshaded` jar for the actual subject of this PR, and an incidental `closure-compiler-main` parent pom that also has to be released to Maven central (because the shaded and unshaded jars both depend on it).  I regret not devoting more time to naming.

**Comment by Dominator008** [comment]
@michaelhixson I think the naming is fine.

**Pull request closed without merging**
