### PR TITLE
Add ace.js extern.

### PR DESCRIPTION
**Pull request by superkonduktr**
This PR proposes to add an extern for [Ace.js](https://ace.c9.io/), a popular in-browser code editor.
The extern file is fully based on the [official Ace API Reference](https://ace.c9.io/#nav=api) with some minor corrections (spelling and missing lines in documentation).
Some parts of the API tagged `undocumented` in the Reference are also marked as such in the extern file.

---
This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1800)

### CODE REVIEW

**Comment by Dominator008** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/externs/ace-1.2.3.js, line 21 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1800#-KI83VvYtKceqgyuhUYs:-KI83VvYtKceqgyuhUYt:-1587506510) ([raw file](https://github.com/google/closure-compiler/blob/e49e95a3b3686ac4ba128add05d50ca5a8af6bde/contrib/externs/ace-1.2.3.js#L21)):*
> ```JavaScript
>  * @see https://ace.c9.io/#nav=api
>  * @externs
>  * @license
> ```

This separate license should be removed. The file should only be licensed with the Apache License above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1800)*

**Comment by Dominator008** [comment]
@superkonduktr Looks great, thanks! The only issue I noticed is the separate license which should be removed.

**Comment by superkonduktr** [comment]
@Dominator008 
Hello Michael, thank you for your review. I removed the extra license.

**Comment by Dominator008** [comment]
@superkonduktr Looks good, thanks!

**Comment by dimvar** [comment]
This is great, thanks!

One thing I noticed is that there are several places where a type is implicitly nullable, such as `Element` here:
https://github.com/superkonduktr/closure-compiler/blob/255e3346d1f8b02e57c41086a8ad1e1002642311/contrib/externs/ace-1.2.3.js#L40

Do you mind switching those to either non-nullable (`!Element` in this case) or explicitly nullable (`?Element` in this case) ? We've seen that many times people omit the modifiers even though they mean a non-nullable type, and end up using looser types without realizing it.

**Comment by Dominator008** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1800)*

**Comment by superkonduktr** [comment]
@dimvar Thanks! I switched the types to non-nullable as you suggested.

**Comment by Dominator008** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1800)*

**Comment by dimvar** [comment]
I still see a bunch of implicitly nullable arrays and objects, eg, if you search for `{Array` or `{Object` you'll find them.

**Comment by superkonduktr** [comment]
@dimvar 
I fixed the rest of the `Array`s and `Object`s, including `Array<Object>`s. I hope I didn't miss anything this time!

**Comment by dimvar** [comment]
LGTM

**Comment by dimvar** [comment]
@superkonduktr 
I will be merging this internally soon. FYI, I had to make changes in about 20 places where our tests complained. When this commit lands externally, feel free to check out the merge conflicts and make the necessary changes in a new PR.

**Pull request closed without merging**
