### PR TITLE
Fixing Eclipse configuration

### PR DESCRIPTION
**Pull request by supersteves**
Removing Eclipse classpath and project files, which still referred to the lib folder removed when Ant support was dropped a few weeks ago.
Updating readme to direct users to build their eclipse config with Maven and to manually fix the build path. 
Ignoring all Eclipse .classpath and .project files in git.

### CODE REVIEW

**Comment by supersteves** [comment]
Note, I tried to fix the pom.xml's to auto-generate the correct source exclusions for GWT sources as per [here](http://maven.apache.org/plugins/maven-eclipse-plugin/examples/specifying-source-path-inclusions-and-exclusions.html), but couldn't get it to work; it put the exclusions on all _but_ the main src classpathentry. So I put it in the readme instead.

**Comment by ChadKillingsworth** [comment]
See #1268 as well.

**Comment by supersteves** [comment]
any chance this could get accepted? would save me some admin each time I debug/test the compiler.

**Comment by MatrixFrog** [comment]
LGTM. Bradford were you going to go ahead an import this?

**Comment by brad4d** [comment]
Sure, I'll do that.

**Comment by brad4d** [comment]
@ChadKillingsworth does accepting this PR mean we can drop #1268?

**Comment by ChadKillingsworth** [comment]
Yes

**Comment by dimvar** [comment]
@supersteves can you squash commits? Our script that imports PRs doesn't handle multiple commits.

**Comment by supersteves** [comment]
@dimvar done.

**Comment by brad4d** [comment]
screen shot 2016-08-18 at 17 41 12

I get this error dialog box when I try to follow the instructions on my mac.

Is this expected?

**Comment by ChadKillingsworth** [comment]
@brad4d That's what this section fixed: https://github.com/google/closure-compiler/pull/1268/files#diff-4097d89b1e411c4a3000ccc2b099e40aR71

**Comment by brad4d** [comment]
@ChadKillingsworth, I guess I misunderstood then.
This PR deletes .classpath and .project, but #1268 updates them.

I thought you said this PR made that one obsolete.
Please clarify.

**Comment by ChadKillingsworth** [comment]
The updates to the pom.xml from #1268 fix the exact error message you see. That's the only thing from that PR that's applicable.

I don't use eclipse anymore. But there was a way within eclipse to have it fix that error - which generates the updates to the pom.xml file. I don't recall those steps though.

**Comment by supersteves** [comment]
I've revised the instructions and squashed again - namely, disregard the two warnings. I'm not sure which part of @ChadKillingsworth's original PR to use to prevent the plugin warning, nor how to automatically configure the build path exclusions. For a future iteration, perhaps. But instructions are now clear and re-tested.

**Comment by brad4d** [comment]
Thanks a lot @supersteves.
I'll retry importing.

**Pull request closed without merging**
