### PR TITLE
Add externs for hls.js

### PR DESCRIPTION
**Pull request by IvanRF**
Externs definition for the JavaScript library [hls.js](https://github.com/video-dev/hls.js)

### CODE REVIEW

**Comment by IvanRF** [comment]
I must add that I tested the player with a basic code like the one on the _Getting Started_ docs of `hls.js` and the player on the resulting minification works fine.
Before:
```
if (Hls.isSupported()) {
	var video = document.getElementById("video");
	var src = video.dataset.source;
	var hls = new Hls();
	hls.loadSource(src);
	hls.attachMedia(video);
	hls.on(Hls.Events.MANIFEST_PARSED, function() {
		video.play();
	});
}
```

After:
```
if(Hls.isSupported()){var a=document.getElementById("video"),b=a.dataset.source,c=new Hls;c.loadSource(b);c.attachMedia(a);c.on(Hls.Events.MANIFEST_PARSED,function(){a.play()});
```

**Comment by dimvar** [comment]
Hi Ivan, we don't really host externs for all libraries, only for a few very popular ones.

**Comment by MatrixFrog** [comment]
You can add it to https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries if you like.

**Comment by MatrixFrog** [comment]
(Er, I mean, host it somewhere else, and then link to it from that wiki page)

**Comment by IvanRF** [comment]
@MatrixFrog I just edited the wiki page, thanks!

**Pull request closed without merging**
