### PR TITLE
Publicize the source_map_input flag

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Now that the compiler composes source maps, document the method for passing them to the compiler.

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
Ping - this one is a quick import.

**Comment by brad4d** [comment]
For some reason importing the change failed.
I'm investigating.

**Comment by brad4d** [comment]
I don't know what the problem was, but it's easy enough to just manually apply the change.
Testing that now.

**Comment by brad4d** [comment]
Sent for internal review.

**Pull request closed without merging**
