### PR TITLE
Improve w3c_batterystatus.js

### PR DESCRIPTION
**Pull request by realityforge**
With this PR I split the commits into small targeted commits. I am hoping this makes it easier to consume. If not I can split the PR or squash the commits.

### CODE REVIEW

**Comment by realityforge** [comment]
It should be noted that I assume that when this lands in closure, then google/elemental2#108 will need to be simultaneously applied.

**Comment by brad4d** [comment]
Created internal issue http://b/130163668

**Comment by brad4d** [comment]
@jDramaix it looks like we would need to coordinate this PR and google/elemental2#108 to avoid breaking things.
Are you interested in doing that now?

**Comment by jDramaix** [comment]
yep let coordinate. I've commented in the internal buganizer ticket.

**Comment by brad4d** [comment]
With help from @jDramaix I've imported a combination of the two PRs and sent the resulting change for testing.

**Pull request closed without merging**
