### PR TITLE
Added QUnit

### PR DESCRIPTION
**Pull request by elipoultorak**

### CODE REVIEW

**Comment by elipoultorak** [comment]
I signed it!

**Comment by MatrixFrog** [comment]
It's usually a good idea to put `/** @externs */` at the top of an externs file. Other than that, I don't know QUnit but since this is generated I assume it's reasonably correct.

**Comment by ChadKillingsworth** [comment]
All of those functions will be assumed to be:

```js
/**
 * @param {...*} args
 * @param return {*}
 */
function fnc(args) {}
```

We have historically only accepted externs into the official repo that have type information.

**Comment by MatrixFrog** [comment]
+1, let's not merge this. However if you want to put it somewhere else we would be happy to link to it from our wiki.

**Pull request closed without merging**
