### PR TITLE
Aggressively inline IIFEs even when assumeClosuresOnlyCaptureReferences is false

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Take 2 at fixing #2100. Follow up to discussion at #2103.

Tweak the function inlining heuristic such that it is much more aggressive about inlining IIFEs.

### CODE REVIEW

**Comment by Dominator008** [comment]
I think we tried something similar but it was rolled-back: https://github.com/ChadKillingsworth/closure-compiler/commit/0660acdb4691cade499563c663a2c83243d0c4b2.

**Comment by ChadKillingsworth** [comment]
Hmm your right. I had thought 0660acd had done it somewhat differently, but apparently not. I'll keep checking.

**Comment by ChadKillingsworth** [comment]
Can someone lookup the failure cases that led to the rollback?

**Comment by dimvar** [comment]
> Can someone lookup the failure cases that led to the rollback?

Unfortunately, I didn't record what the exact failure was, just the generic rollback message that it was an IIFE with local variables.

**Comment by ChadKillingsworth** [comment]
I'm closing this. I looked extensively through the InlineFunctions pass. While the changes from the new ConvertIIFEArgsToVars pass could be added into InlineFunctions, it would simply serve to make a complicated process more so. There isn't any real benefit from combining the two.

It may prove that ConvertIIFEArgsToVars is unsafe for exactly the same reasons that the aggressive inlining of IIFEs, but it's worth a try.

Ideally, ConvertIIFEArgsToVars would be a peephole optimization, but it needs to run only at the beginning of the optimizations loop and Peephole optimizations run much more frequently..

**Pull request closed without merging**
