### PR TITLE
Fixes #2605 - CommonJS missing semicolon check.

### LINKED ISSUE #2605: ES6 or CommonJS modules cause "Missing semicolon" errors
I'm seeing erroneous `WARNING - Missing semicolon` errors when using **ES6** or **CommonJS** modules (with `jscomp_warning` turned on for all checks). The warnings do not appear for Closure Library (goog) modules.

It sounds like Closure Compiler transpiles ES6 and CommonJS to Closure Library modules, so I wonder if a missing semicolon error is introduced during that process?

Here are 3 simple test examples, one for each module system. They each have an entry point test.js file that imports a module. I've included the module and test code for each, as well as the output of the command.

All commands were run with the v20170626 version of the compiler:
```
$ java -jar ./compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20170626
Built on: 2017-06-30 12:25
```

####  ./module.js
```
module.exports = 1;
```

#### ./test.js
```
const value = require('./module.js');

console.log(value);
```

```
$ java -jar ./compiler.jar \
  --jscomp_warning=* \
  --js=./test.js \
  --js=./module.js \
  --entry_point=./test.js
  --process_common_js_modules

./module.js:1: WARNING - Missing semicolon
module.exports = 1;
^^^^^^^^^^^^^^^^^^^

./test.js:1: WARNING - Missing semicolon
const value = require('./module.js');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 error(s), 2 warning(s), 100.0% typed
var module$module=1;var value=module$module;console.log(module$module);
```

Result: 2 Warnings for Missing semicolon on lines that clearly have a semicolon.

#### ./module.js
```
export const value = 1;
```

#### ./test.js
```
import { value } from './module.js';

console.log(value);
```

```
$ java -jar ./compiler.jar \
  --jscomp_warning=* \
  --js=./test.js \
  --js=./module.js \
  --entry_point=./test.js

./module.js:1: WARNING - Missing semicolon
export const value = 1;
^^^^^^^^^^^^^^^^^^^^^^^

./module.js:1: WARNING - Missing semicolon
export const value = 1;
       ^^^^^^^^^^^^^^^

./module.js:1: WARNING - Missing semicolon
export const value = 1;
             ^^^^^^^^^

./test.js:1: WARNING - Missing semicolon
import { value } from './module.js';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 error(s), 4 warning(s), 100.0% typed
var module$module={},value$$module$module=1;module$module.value=value$$module$module;var module$test={};console.log(module$module.value);
```

Result: 4 Warnings for Missing semicolon on lines that clearly have a semicolon.

#### ./module.js
```
goog.module('test.module');

const value = 1;

exports = {value};
```

#### ./test.js
```
goog.module('test');

const {value} = goog.require('test.module');

console.log(value);
```

```
$ java -jar ./compiler.jar \
  --jscomp_warning=* \
  --js=./test.js \
  --js=./module.js \
  --entry_point=goog:test

var module$exports$test$module={value:1};var module$exports$test={};console.log(module$exports$test$module.value);
```

Result: No warnings with Closure Library (goog.module).

### PR DESCRIPTION
**Pull request by jameskeane**
`ProcessCommonJSModules` creates a top-level 'initModule' var that
represents the exported module. The initModule `Node` is given
source info from the entire script node.

When the script being processed contains a newline after the last
statement, the erroneous missing semicolon is emitted since it is
not expecting the source information of a `var` to include a new
line.

The most minimal example:
```javascript
module.exports = 1;
[there has to be a \n here]
```
Compiled with `--jscomp_error=lintChecks --process_common_js_modules`

### CODE REVIEW

**Comment by jameskeane** [comment]
I can't figure out how to turn lint checks on in `ProcessCommonJSModulesTest`.

`Es6RewriteModulesTest` seems to call `options.setWarningLevel(DiagnosticGroups.LINT_CHECKS...` but I don't think it does anything.

**Comment by jameskeane** [comment]
I signed it!

**Comment by jameskeane** [comment]
Oof, looks like I goofed. This still throws an error:
```javascript
class Example {

}

module.exports = Example;
```

**Comment by jameskeane** [comment]
The issue above is similar (but unrelated) bug due to es6 rewriting.

**Comment by blickly** [comment]
I agree it seems weird that `Es6RewriteModulesTest` calls `options.setWarningLevel(DiagnosticGroups.LINT_CHECKS...`; I think we should remove that line. (Maybe in the past there were some lint checks included in this pass?)

If you want to try it out, you should be able to add the lint checks to getProcessor(), but I wouldn't want to check that in, since then the `Es6RewriteModulesTest` wouldn't really be a unit test

**Comment by blickly** [comment]
Is there a test that can be included here?

**Comment by jameskeane** [comment]
@blickly I couldn't figure out how to add it to `Es6RewriteModulesTest`, so I've enabled `processCommonJSModules` in `CheckMissingSemicolonTest`.

**Comment by blickly** [comment]
Oops, sorry to miss this update for so long!

Just took another look, and I think that the unit tests can't run arbitrary other passes, and it looks like these new tests are passing without the change to lint/CheckMissingSemicolon.java. So even though I generally prefer tests over not having them, I don't think these tests hold their weight.

**Comment by lauraharker** [comment]
Closing since there's been no response for about a year.

**Pull request closed without merging**
