### PR TITLE
Fix: Map/Set polyfill should store -0 in keys as +0

### PR DESCRIPTION
**Pull request by teppeis**
- https://www.ecma-international.org/ecma-262/8.0/#sec-map.prototype.set
- https://www.ecma-international.org/ecma-262/8.0/#sec-set.prototype.add
- https://kangax.github.io/compat-table/es6/#test-Map_-0_key_converts_to_+0
- https://kangax.github.io/compat-table/es6/#test-Set_-0_key_converts_to_+0

### CODE REVIEW

**Comment by brad4d** [comment]
@teppeis are you sure this change is really needed?
I mean, did you actually see a case in running code where our polyfill for Map or Set treated +0 and -0 differently?

@shicks what do you think?

**Comment by teppeis** [comment]
@brad4d 
In actual code, `-0` is rarely used.
However, I think that polyfill should conform to the specification as much as possible if it doesn't have performance or other issues obviously.

**Comment by brad4d** [comment]
@teppeis what I'm saying is I suspect our code actually handles `-0` correctly already even though that isn't visible in the code.
Can you show otherwise?

**Comment by teppeis** [comment]
@brad4d These tests are failed in current Closure Compiler polyfill.

```js
const map = new Map().set(-0, 'foo');
assertEquals(Infinity, 1 / map.keys().next().value);

const set = new Set([-0]);
assertEquals(Infinity, 1 / set.keys().next().value);
```

**Comment by brad4d** [comment]
imported and sent for internal review

**Comment by brad4d** [comment]
added a few more test cases
starting internal submission

**Comment by teppeis** [comment]
@brad4d @lauraharker thanks!

**Pull request closed without merging**
