### PR TITLE
Rewrite of jQueryAjaxSettings type to avoid circular typedef

### PR DESCRIPTION
**Pull request by vobruba-martin**
Current jQuery extern file shows warning "Circular typedefs/enums are not allowed" when using NTI.

### CODE REVIEW

**Comment by dimvar** [comment]
Can you switch @interface to @record? Also, can you leave a blank line before each property definition?

**Comment by vobruba-martin** [comment]
Updated. Where can I find documentation for the @record tag? I'm using https://developers.google.com/closure/compiler/docs/js-for-compiler but it seems outdated.

**Comment by blickly** [comment]
Currently we have a wiki page:
https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler

The hope is to eventually make @interface structural as well.

**Comment by dimvar** [comment]
LGTM. Can you squash the commits before we merge the PR?

**Comment by ChadKillingsworth** [comment]
Looks like every reference of `jQueryAjaxSettings` is a union with `Object<string, *>`, so this shouldn't break anything. Otherwise we would need more testing.

**Comment by vobruba-martin** [comment]
@dimvar Is it ok now?

**Pull request merged**
