### PR TITLE
Mark function parameter as non nullable

### PR DESCRIPTION
**Pull request by fredj**
The function parameter of:
 * `Array.prototype.reduce`
 * `Array.prototype.reduceRight`
 * `Array.prototype.every`
 * `Array.prototype.filter`
 * `Array.prototype.forEach`
 * `Array.prototype.map`
 * `Array.prototype.some`

Must be not null

### CODE REVIEW

**Comment by fredj** [comment]
This will certainly break closure-library

**Comment by concavelenz** [comment]
I'm pretty sure, this is "?function..." because of the breakage "!function..." caused.

**Comment by MatrixFrog** [comment]
For most of these, I'm pretty sure there is no good reason to ever pass null. But fixing all the types in Closure Library (not to mention everywhere else at Google) may not be feasible :(

**Comment by dimvar** [comment]
OK, seems like the google-internal cleanup isn't high priority for us to accept this PR. Closing.

**Pull request closed without merging**
