### PR TITLE
Copy polymer externs into contrib

### PR DESCRIPTION
**Pull request by rictic**
Copied over from https://raw.githubusercontent.com/PolymerLabs/polymer-externs/master/polymer.externs.js as recommended by https://github.com/PolymerLabs/polymer-externs/issues/44

/cc @ChadKillingsworth

[Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1432)

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
Awesome. This worked great in my project.

Do you want to change the name to `polymer-1.x.js`? I ask because we've had lots of people get confused with jQuery externs that didn't quite cover the released versions. The latest Polymer is 1.2.3.

**Comment by MatrixFrog** [comment]
Can you do this internally so that we can update the build targets too?

**Comment by concavelenz** [comment]
@rictic any update on this?

**Comment by ChadKillingsworth** [comment]
@MatrixFrog Were you going to help submit this internally? I'd like to get this one done. FYI this PR is out of date as there are more recent changes at https://github.com/PolymerLabs/polymer-externs/blob/master/polymer.externs.js

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/f7c7ead1e72ea2bf68384df6f419933e4b94f24f.

**Pull request closed without merging**
