### PR TITLE
Reducing eclipse warnings

### PR DESCRIPTION
**Pull request by supersteves**
There were 220 warnings showing in Eclipse, and I doubt these would ever get fixed. This focuses on the more meaningful warnings, 17 of them:
Unused local variables
Unused private methods
Generic type params on inner class hiding outer class params

### CODE REVIEW

**Comment by dimvar** [comment]
What is this new settings file org.eclipse.jdt.core.prefs? I doubt that we want it in the codebase.

**Comment by supersteves** [comment]
It's a project-specific configuration for errors/warnings in Eclipse. If you discard this PR, curious how do you control IDE warning settings in your team? Do you have a google wide workspace configuration? Because the defaults show 220 warnings most of which are not necessary.

**Comment by ChadKillingsworth** [comment]
@supersteves They don't use Eclipse.

@dimvar We have other [eclipse-specific files](https://github.com/google/closure-compiler/blob/master/.classpath) and our readme gives instructions for building within eclipse. I asked on the mailing list how many use IntelliJ products vs Eclipse and a good number of people responded that they used Eclipse.

Personally I haven't used Eclipse for years, but if we are going to continue officially providing instructions within Eclipse, this would be nice to add.

**Comment by dimvar** [comment]
> how do you control IDE warning settings in your team?
Each team member uses their own editor/settings. I use Emacs, others use IDEs (but not just Eclipse).

> if we are going to continue officially providing instructions within Eclipse, this would be nice to add.
I'm not super convinced that we need to have a lot of IDE specific information in the codebase. I'll let others chime in if they think it's appropriate/useful.

**Comment by supersteves** [comment]
I thought you would have some project specified rules for what is considered an error/warning in the codebase - quality standards. That's all this is, not personal preferences.

**Comment by dimvar** [comment]
> I thought you would have some project specified rules for what is considered an error/warning in the codebase

There is an internal linter that helps us with this. We generally don't go and fix them across the codebase, we only see the warnings in files we edit and we fix them in those.

> quality standards. That's all this is, not personal preferences

Right, yes, quality is important. But since we have a separate setup for warnings, is it too cumbersome for you to have the settings file in your own codebase only?

**Comment by supersteves** [comment]
@dimvar of course not, just thought that if you have project settings for eclipse in VCS, you would want to turn off meaningless warnings. Absolutely no inconvenience to keep the same settings file non VCS tracked.

**Comment by dimvar** [comment]
Great. I think then we can close this PR.

**Pull request closed without merging**
