### PR TITLE
Skip devirtualization of @nocollapse prototype methods

### LINKED ISSUE #2420: @nocollapse seems not to work properly
As discussed [here](http://stackoverflow.com/questions/43187947/preserve-prototypes-in-advanced-mode/), compiler seems to not work properly when using `@collapse` JSDoc tag. The compiler is properly not collapsing objects attributes but is still collapsing objects prototypes when using the tag.

Example of code before compilation :

```javascript
/** @constructor */
function MyClass() = { // Some code }
/** @nocollapse */
MyClass.someAttribute = function(someParam) { // Some code };
/** @nocollapse */
MyClass.prototype.someFunc = function() { // Some code calling someOtherFunc };
/** @nocollapse */
MyClass.prototype.someOtherFunc = function(someParam) { // Some code };
```

Example of code after compilation :

```javascript
function MyCompiledClass = { // Some code }
MyCompiledClass.someCompiledAttribute = function(someParam) { // Some code };
MyCompiledClass.prototype.someCompiledFunc = function() { // Some code calling someOtherFunc }
function someOtherCompiledFunc(that, someParam) = { // Some code }
```

I've tried to set `@this` and `@preserve` tags without success. Using `@export` is not a good solution.

Compiler flags are :
- compilation_level : 'ADVANCED'
- warning_level : 'QUIET'
- language_in : 'ECMASCRIPT5_STRICT'

Google-Closure-Compiler versions tested :
- v20160315
- v20170218
- master at ee44867683988d37c9cdb1b5c9557fe984c87135

### PR DESCRIPTION
**Pull request by DavidANeil**
Resolves #2420
Relates to https://github.com/angular/tsickle/issues/1164

### CODE REVIEW

**Comment by lauraharker** [comment]
I share John's concern from https://github.com/google/closure-compiler/issues/2420#issuecomment-293324401 that even if `@nocollapse` prevented devirtualization, it would still be possible to still run into problems with other optimizations on prototype methods. It's certainly possible that for your specific use case, devirtualization is the only problem, but changing your code even slightly could conceivably cause some other optimization to break things.

Could you share some more details on what you want this for?

------

If it helps, here's a more concrete and very contrived example of what I mean by "run into problems with other optimizations". Take this code that loops over a prototype:

``` javascript
/** @unrestricted */
class MyClass {
  f1(p) { console.log('f1 called with ' + p); }
  f2(p) { console.log('f2 called with ' + p); }
  f3(p) { console.log('f3 called with ' + p); }
}

const mc = new MyClass();

for (const p of Object.getOwnPropertyNames(MyClass.prototype)) {
  if (p === 'constructor') {
    continue;
  }
  mc[p](0);
}

mc.f1(3);
```

Uncompiled, this prints:

```
f1 called with 0
f2 called with 0
f3 called with 0
f1 called with 3
```

Of course if I enable full optimizations including devirtualization in the debugger, both `f2` and `f3` are deleted: [debugger link](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540unrestricted%2520*%252F%250Aclass%2520MyClass%2520%257B%250A%2520%2520f1(p)%2520%257B%2520console.log('f1%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f2(p)%2520%257B%2520console.log('f2%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f3(p)%2520%257B%2520console.log('f3%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%257D%250A%250Aconst%2520mc%2520%253D%2520new%2520MyClass()%253B%250A%250Afor%2520(const%2520p%2520of%2520Object.getOwnPropertyNames(MyClass.prototype))%2520%257B%250A%2520%2520if%2520(p%2520%253D%253D%253D%2520'constructor')%2520%257B%250A%2520%2520%2520%2520continue%253B%250A%2520%2520%257D%250A%2520%2520mc%255Bp%255D(0)%253B%250A%257D%250A%250Amc.f1(3)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26OPTIMIZE_CONSTRUCTORS%3Dtrue%26OPTIMIZE_ARGUMENTS_ARRAY%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_PSEUDO_NAMES%3Dtrue%26PARSE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue).

But disabling devirtualization entirely (via the DEVIRTUALIZE_METHODS checkbox) is not enough to get the compiler to preserve the pre-compiled behavior. Here are some examples:
 * disabling just DEVIRTUALIZE_METHODS still causes f1 and f2 to be deleted: [link](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540unrestricted%2520*%252F%250Aclass%2520MyClass%2520%257B%250A%2520%2520f1(p)%2520%257B%2520console.log('f1%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f2(p)%2520%257B%2520console.log('f2%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f3(p)%2520%257B%2520console.log('f3%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%257D%250A%250Aconst%2520mc%2520%253D%2520new%2520MyClass()%253B%250A%250Afor%2520(const%2520p%2520of%2520Object.getOwnPropertyNames(MyClass.prototype))%2520%257B%250A%2520%2520if%2520(p%2520%253D%253D%253D%2520'constructor')%2520%257B%250A%2520%2520%2520%2520continue%253B%250A%2520%2520%257D%250A%2520%2520mc%255Bp%255D(0)%253B%250A%257D%250A%250Amc.f1(3)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26OPTIMIZE_CONSTRUCTORS%3Dtrue%26OPTIMIZE_ARGUMENTS_ARRAY%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_PSEUDO_NAMES%3Dtrue%26PARSE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
 *  if I enable only the OPTIMIZE_CALLS optimization (https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/OptimizeCalls.java), and nothing else, that alone is enough to break this code ([link](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540unrestricted%2520*%252F%250Aclass%2520MyClass%2520%257B%250A%2520%2520f1(p)%2520%257B%2520console.log('f1%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f2(p)%2520%257B%2520console.log('f2%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f3(p)%2520%257B%2520console.log('f3%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%257D%250A%250Aconst%2520mc%2520%253D%2520new%2520MyClass()%253B%250A%250Afor%2520(const%2520p%2520of%2520Object.getOwnPropertyNames(MyClass.prototype))%2520%257B%250A%2520%2520if%2520(p%2520%253D%253D%253D%2520'constructor')%2520%257B%250A%2520%2520%2520%2520continue%253B%250A%2520%2520%257D%250A%2520%2520mc%255Bp%255D(0)%253B%250A%257D%250A%250Amc.f1(3)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_PSEUDO_NAMES%3Dtrue%26PARSE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)):

Why does OptimizeCalls break this pattern? Closure Compiler thinks that `f1` is only ever called as `mc.f1(3);`; and it replaces the parameter `p` with `var p = 3;` inside `f1`. That messed up the loop over the prototype properties.

``` javascript
'use strict';
class MyClass {
  f1() {
    var p = 3;
    console.log("f1 called with " + p);
  }
  f2(p) {
    console.log("f2 called with " + p);
  }
  f3(p) {
    console.log("f3 called with " + p);
  }
}
const mc = new MyClass();
for (const p of Object.getOwnPropertyNames(MyClass.prototype)) {
  if (p === "constructor") {
    continue;
  }
  mc[p](0);
}
mc.f1();
```

i.e. - OptimizeCalls, and also other optimizations in the compiler, make a similar assumption as DevirtualizeMethods that they can see all call sites for unexported, unquoted prototype methods.

**Comment by DavidANeil** [comment]
This change enables tsickle to emit `@nocollapse @noinline` on decorated prototype methods with the following guarantees:
1) If the method is otherwise unused, then the decorator will not prevent it from being eliminated.
2) If the method is kept, then it will be present at the expected place on the prototype.

(2) is needed because the decorator is emitted as something like so:
```javascript
class MyClass {
    /** @nocollapse @noinline */
    f1() {
    }
}
__decorate([
    MyDecoratorFunction,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", void 0)
], MyClass.prototype, __tsickle_googReflect.objectProperty("f1", Foo.prototype), null)
```

Without the change of this PR, the `__decorate` utility would be unable to consistently locate the (renamed) `f1` on `MyClass.prototype` because the method might have been moved off of the prototype.

I'm not certain `@noinline` is actually strictly required, but I plan on adding it just in case.

**Comment by lauraharker** [comment]
I see, what about making DevirtualizeMethods understand the property reflection call instead?

It uses the OptimizeCalls class to detect property references, so probably we would start by adding a case below the one for regular property accesses: https://github.com/google/closure-compiler/blob/f156ff38bc1c2b727d898a5320d6c83db0ce1340/src/com/google/javascript/jscomp/OptimizeCalls.java#L447-L450

And do something similar to the RenameProperties pass to detect reflection: https://github.com/google/closure-compiler/blob/f156ff38bc1c2b727d898a5320d6c83db0ce1340/src/com/google/javascript/jscomp/RenameProperties.java#L309-L318.

Then there might be some more work in OptimizeCalls or DevirtualizeMethods to get it to back off when it sees reflection, similar to the backoff for references like `console.log(Foo.prototype.f1);` ([example](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540unrestricted%2520*%252F%250Aclass%2520MyClass%2520%257B%250A%2520%2520f1(p)%2520%257B%2520console.log('f1%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f2(p)%2520%257B%2520console.log('f2%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%2520%2520f3(p)%2520%257B%2520console.log('f3%2520called%2520with%2520'%2520%252B%2520p)%253B%2520%257D%250A%257D%250A%250Aconst%2520mc%2520%253D%2520new%2520MyClass()%253B%250A%250Afor%2520(const%2520p%2520of%2520Object.getOwnPropertyNames(MyClass.prototype))%2520%257B%250A%2520%2520if%2520(p%2520%253D%253D%253D%2520'constructor')%2520%257B%250A%2520%2520%2520%2520continue%253B%250A%2520%2520%257D%250A%2520%2520mc%255Bp%255D(0)%253B%250A%257D%250A%250A%252F%252F%2520this%2520reference%2520forces%2520devirtualization%2520to%2520back%2520off%250Aconsole.log(MyClass.prototype.f3)%253B%250A%250A%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26OPTIMIZE_CONSTRUCTORS%3Dtrue%26OPTIMIZE_ARGUMENTS_ARRAY%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_PSEUDO_NAMES%3Dtrue%26PARSE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)).

That change seems more inline with Closure Compiler's existing support for reflective accesses.

**Comment by lauraharker** [comment]
@DavidANeil can we close this PR now that https://github.com/google/closure-compiler/pull/3967 is in?

**Pull request closed without merging**
