### PR TITLE
Prevent arrow functions from being improperly inlined

### LINKED ISSUE #3756: InlineSimpleMethods makes a semantic change in ES2015+
Given the following input code:
```javascript
class Holder {
    constructor() {
        this.val = {internal: true};
        this.context =  {getVal: () => this.val}
    }
}

console.log(new Holder().context.getVal().internal);
```

Outputs:
```javascript
class a {
  constructor() {
    this.g = {h:!0};
    this.i = {j:() => this.g};
  }
}
console.log((new a).i.g.h);
```

The `InlineSimpleMethods` replaces the call of `getVal()` with `val`, which is incorrect because the `this` in the definition of `getVal` is not `context`, but rather `Holder`.
This is not a problem in ES5, because the arrow function is already rewritten before running this pass.

### PR DESCRIPTION
**Pull request by DavidANeil**
Closes #3756.

### CODE REVIEW

**Comment by blickly** [comment]
And thanks for the fix as well!

This looks good to me, so I'll work on getting it imported right away

**Comment by blickly** [comment]
This PR is now merged. Thanks!

One suggested improvement I heard during review was: only backing off for arrow functions that reference `this`/`super`/`arguments` rather than all arrow functions.  This would still avoid the bug of #3756, while at the same time being able to inline arrow functions that don't reference those references from outer scopes (the more common case).

**Comment by DavidANeil** [comment]
My understanding was that `isPropertyTree` is a recursive function that only returns true if the lhs of the returned property access is `this`, so I feel like what you've suggested is already the case.

**Comment by blickly** [comment]
I think this might be best demonstrated with another unit test, similar to the one you created already, but checking that arrow functions can be inlined, something like:

```
    test(
        lines(
            "class Holder {",
            "    constructor() {",
            "        this.val = {internal: true};",
            "        this.context = {getVal: () => 5}",
            "    }",
            "}",
            "",
            "console.log(new Holder().context.getVal().internal);"),
        lines(
            "class Holder {",
            "    constructor() {",
            "        this.val = {internal: true};",
            "        this.context = {getVal: () => 5}",
            "    }",
            "}",
            "",
            "console.log(new Holder().context.val.internal);"));
```

If that unit test passes, that would prove that arrow functions can still be inlined by the pass.

**Comment by blickly** [comment]
I filed https://github.com/google/closure-compiler/issues/3764 to track this work.

**Pull request merged**
