### PR TITLE
Add missing extern for `Array.from` (update of #1297)

### PR DESCRIPTION
**Pull request by Dominator008**

### CODE REVIEW

**Comment by Dominator008** [comment]
@ambar I've updated some type annotations here.

**Comment by ambar** [comment]
Thanks!

**Comment by MatrixFrog** [comment]
We landed an Array.from extern recently and it broke some internal projects. We'll probably have to do this one internally first and then push it out.

**Comment by MatrixFrog** [comment]
LGTM but it looks like it needs a rebase, which should also kick off a new Travis run.

**Comment by Dominator008** [comment]
The "pull/1297" ref is read-only, reapplying this in #1335.

**Pull request closed without merging**
