### PR TITLE
Add the timeout.cancel function from angular 1.5

### PR DESCRIPTION
**Pull request by sbrunner**
Get from https://github.com/google/closure-compiler/blob/master/contrib/externs/angular-1.5.js#L2575-L2589

### CODE REVIEW

**Comment by mprobst** [comment]
@dpurp did we leave out the reopening + `$timeout.cancel` on purpose?

**Comment by dpurp** [comment]
Yes and no.  It was actually moved to [angular-1.6-function-properties.js](https://github.com/google/closure-compiler/blob/master/contrib/externs/angular-1.6-function-properties.js), since it didn't compile with strict checks due to an issue with Closure compiler.  It errored with properties-on-functions, wherein two functions have properties with the same name (`$timeout` and `$interval`).

The issue was fixed internally a few weeks ago, but I have been waiting on a public release of closure.  Since that happened last week, I *should* be merge `function-properties` back into the main file.  I'll look into that today.

**Comment by sbrunner** [comment]
Thanks in advance @dpurp :-)

**Comment by dpurp** [comment]
Exported to github in: https://github.com/google/closure-compiler/commit/3a99f4ddacee6173a2d00e2803612628a79a8407

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request closed without merging**
