### PR TITLE
When composing source maps, utilize source content provided in an input map

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
I discovered that with the JS version, source maps are not composed. This turned out to be from a bug where we only use the sourcesContent from an input source map to display errors and we only load the content from disk.

In addition, we only composed source maps if the content of the original file could be loaded. This wasn't needed.

Adds support to source maps where content provided in an input source map can be forwarded to the output source map. Also allows the GWT version to compose source maps when the input source map provides the original content in the `sourcesContent` field.

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
Fixed. Let me know if you want me to squash the commits.

**Comment by blickly** [comment]
LGTM, let's squash and I'll bring it in! Thanks Chad

**Comment by ChadKillingsworth** [comment]
Hmm 200824732982ab6032e53de74eee59a49c775bc0 did some of the same work. I'll have to see what of my changes still needs applied.

**Comment by ChadKillingsworth** [comment]
@blickly squashed. This is significantly simpler due to 2008247 handling many of the same concerns.

**Comment by ChadKillingsworth** [comment]
@blickly I prefer to have the tests, but they were not actually failing (at least when I ran it). I'm not sure why. A lot of things changed with the other commit and I haven't had a chance to fully understand the implications.

**Pull request closed without merging**
