### PR TITLE
Rework CommonJS hoisting and goog.require/provide insertion order 

### LINKED ISSUE #2345: ProcessCommonJSModules NPE
I'm getting an `NullPointerException` when trying to process CommonJS modules using the latest February compiler. This doesn't seem like the error reported in #2308.

Below is the relevant part of the stacktrace. I'm still trying to come up with a minimal case, as this happens when trying to consume the `aws-sdk` NPM package (which is huge).
```
Caused by: java.lang.NullPointerException
	at com.google.javascript.jscomp.ProcessCommonJSModules.getScopeInsertionPoint(ProcessCommonJSModules.java:242)
	at com.google.javascript.jscomp.ProcessCommonJSModules.access$400(ProcessCommonJSModules.java:42)
	at com.google.javascript.jscomp.ProcessCommonJSModules$FindImportsAndExports.addGoogProvide(ProcessCommonJSModules.java:556)
	at com.google.javascript.jscomp.ProcessCommonJSModules.process(ProcessCommonJSModules.java:125)
	at com.google.javascript.jscomp.Compiler.processAMDAndCommonJSModules(Compiler.java:1841)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1549)
	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:809)
```

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
This hopefully fixes #2345 

Rather than try to skip over `goog.provide` and `goog.require` calls to insert new nodes, simply delay adding them until after all other module rewriting has completed. This allows these calls to be blindly inserted as the first statement in the script.

### CODE REVIEW

**Comment by anmonteiro** [comment]
This is awesome. I've given this patch a go and can't repro #2345 anymore. Thanks for your work, I can imagine it might have been hard to find a fix without a repro.

**Comment by MatrixFrog** [comment]
Are there any tests we should add here or is this largely a refactoring with no user-visible change?

**Comment by ChadKillingsworth** [comment]
It's simply a refactor.

**Comment by ChadKillingsworth** [comment]
I don't have an exact repo case from the original to add a test for.

**Pull request closed without merging**
