### PR TITLE
constant folding for pow and imul

### PR DESCRIPTION
**Pull request by chrisps**
Just added pow and imul as foldable functions in PeepHoleReplaceKnownMethods.

### CODE REVIEW

**Comment by chrisps** [comment]
I signed it!

**Comment by lauraharker** [comment]
@concavelenz I think you reviewed folding the other Math methods. Can you look at this?

**Comment by brad4d** [comment]
Created internal issue b/122075383

**Comment by concavelenz** [comment]
This can't be accepted without test cases.

**Comment by brad4d** [comment]
@chrisps I'm closing this PR for now.
However, if you update it with tests and reopen it, I will see that and work on it more.

**Pull request closed without merging**
