### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
I'm using this PR to try some tweaks for Travis. I think it's running out of memory.

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
I tried everything I could think of, and lots of tweaks from articles. The GWT compiler is getting killed by the docker host for using too many resources. The only solution I could find was to switch off the container-based build infrastructure at Travis.

Longer build times are far superior to random failures.

**Comment by Dominator008** [comment]
Hmm. It looks like something GWT and Java 7 specific. The Java 8 build's been fine.

**Comment by ChadKillingsworth** [comment]
True - which prompted me to try Oracle's JDK instead of Open JDK. I'll toggle the build a couple more times to see if that's true.

**Comment by ChadKillingsworth** [comment]
Nope. Still flaky.

**Comment by ChadKillingsworth** [comment]
Squashed commits to make this easier

**Pull request closed without merging**
