### PR TITLE
Cleanup Geolocation API to align with spec

### PR DESCRIPTION
**Pull request by realityforge**
1. Rename the following symbols to align with the spec
   - GeolocationPositionError to PositionError
   - GeolocationPositionOptions to PositionOptions
   - GeolocationCoordinates to Coordinates
   - GeolocationPosition to Position
1. Move the UNKNOWN_ERROR, PERMISSION_DENIED and TIMEOUT properties from the PositionError prototype onto the PositionError type
1. Annotate the UNKNOWN_ERROR, PERMISSION_DENIED and TIMEOUT properties as @const
1. Extract typedefs for the success and error callbacks passed to `Geolocation.getCurrentPosition` and `Gelocation.watchPosition`. The typedefs are named using the names in the spec. This improves the types generated in downstream consumers ala Elemental2.
1. Correct the return values of callbacks to return void to align with spec.

### CODE REVIEW

**Comment by realityforge** [comment]
My guess is that this commit is too large to push through the google internal review process. But assuming that the changes seem fine in principle I can break up the commits in whatever way works for you.

**Comment by blickly** [comment]
[Converted your description to a numbered list to help with the discussion]

My gut reaction here is that points 3-5 all sound convincing to me.

2 sounds off to me.  Don't they need to be on the prototype to be part of the @record?

1 sounds reasonable enough if we were starting from scratch, but I'm not convinced that the churn of trying to update everyone with references to the old names are worth it.

**Comment by realityforge** [comment]
The WebIDL for `TIMEOUT` and friends declares them as constants on an interface. The WebIDL spec definition for [constants](https://heycam.github.io/webidl/#idl-constants) declares:

> Constants are not associated with particular instances of the interface on which they appear. It is language binding specific whether constants are exposed on instances.

In javascript that means that they are available on instances ... (yay prototype inheritance). 

So looking at the [WebIDL for PositionError](https://www.w3.org/TR/geolocation-API/#position_error_interface) ... err wait. The interface is marked with the `[NoInterfaceObject]` extended attribute so you are probably correct. I will experiment with this over the weekend.

Hmmm this does make the generated code in elemental2 less useful :(

Anyhoo - I will split out the other changes and send a PR.

**Comment by blickly** [comment]
OK, sounds good.  Closing this one in favor of the smaller more manageable split-off PRs.

Thanks for all the contributions!

**Pull request closed without merging**
