### PR TITLE
Use GWT 2.8.0-beta1 and remove unncessary snapshot repositories

### PR DESCRIPTION
**Pull request by Dominator008**
[Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1363)

### CODE REVIEW

**Comment by MatrixFrog** [comment]
Again, this will require some internal work, but we can probably get it done this week.

**Comment by concavelenz** [comment]
Is something still blocking this?

**Comment by MatrixFrog** [comment]
I'm not sure, I'll look again soon.

**Comment by MatrixFrog** [comment]
I think this is obsoleted by a2bbbd9044fe6c0b6dc3f5e98b83c8609f1bfc06

**Pull request closed without merging**
