### PR TITLE
FR-1045: Add languageout attr to ant CompileTask

### PR DESCRIPTION
**Pull request by artem-snopkov**
https://github.com/google/closure-compiler/issues/1045

### CODE REVIEW

**Comment by artem-snopkov** [comment]
I signed it!

> Artem Snopkov
> artem.snopkov@gmail.com
> 
> 
>

**Comment by artem-snopkov** [comment]
I signed it!

> Artem Snopkov
> artem.snopkov@gmail.com
> 
> 
>

**Comment by artem-snopkov** [comment]
I signed It

**Comment by MatrixFrog** [comment]
lgtm. I'll see if I can get Travis fixed today.

**Pull request merged**
