### PR TITLE
Remove some historic functions that not present in modern browsers

### PR DESCRIPTION
**Pull request by realityforge**
I can break this commit up if you prefer but given how old these properties are and how unlikely they are to be used, it seems like less work to perform change in a single commit

### CODE REVIEW

**Comment by brad4d** [comment]
Well my first attempt at testing failed due to a test infrastructure thing, probably totally unrelated to this change. Trying again...

**Comment by brad4d** [comment]
The good news is that only 2 properties had to be added back.

See the commit I've pushed back to your branch.

Assuming you're cool with that, I'll submit the internal change.

**Comment by realityforge** [comment]
Looks good to me

**Comment by brad4d** [comment]
Submitted internally.
Will be in tomorrow's push to GitHub.

**Comment by realityforge** [comment]
Thanks!

**Pull request closed without merging**
