### PR TITLE
Vibration API (Second Edition)

### PR DESCRIPTION
**Pull request by vobruba-martin**
Based on "W3C Recommendation 18 October 2016"

See https://www.w3.org/TR/vibration/

### CODE REVIEW

**Comment by brad4d** [comment]
@concavelenz this is a new extern file.
Is being standardized by W3C sufficient to add it to standard externs? How do we decide?

**Comment by vobruba-martin** [comment]
BTW i forgot this link http://caniuse.com/#feat=vibration . It may help you with the decision.

**Comment by brad4d** [comment]
LGTM
I'm importing and submitting this.
If you want it added to standard externs, that'll require another PR.

**Comment by vobruba-martin** [comment]
@brad4d Adding a file into externs/browser isn't enough?

**Comment by brad4d** [comment]
@vobruba-martin 
I haven't looked up where it is yet, but according to @concavelenz there's an explicit list of the "standard" externs specified in the order they must be read by the compiler.

I asked him about it because I wondered how we could be certain that `Navigator` gets defined before this new extern defines `Navigator.prototype.vibrate`.

**Comment by ChadKillingsworth** [comment]
It's here: https://github.com/google/closure-compiler/blob/0a0a8ec45ab0df1f5d35bd2881a9dea2b4f7cceb/src/com/google/javascript/jscomp/DefaultExterns.java#L36

**Comment by ChadKillingsworth** [comment]
Only if you need to have a specific order in relation to one of the externs on that list does it need updated. Everything else is just added to the end of the list.

**Comment by brad4d** [comment]
Ah, I see how it works now.
the `pom.xml` file for externs does grab every `.js` file from `externs/browser`.

Close to getting this submitted. Looks like there may be one internal project that I have to tweak, because they created their own version of this extern.

**Comment by brad4d** [comment]
submitted internally

**Comment by brad4d** [comment]
For some reason I don't see my submission in our latest pushes.
I think there must be something I need to do to get the file pushed back to github.

**Pull request closed without merging**
