### PR TITLE
Enable the use_types_for_optmization flag by default

### LINKED ISSUE #812: Turning on the typed-based optimizations by default
This seems to come up a lot. Unless you are well versed in the compiler project, the expectation is that type information would be used for renaming.

* http://stackoverflow.com/q/28318862/1211524
* http://stackoverflow.com/q/28196051/1211524
* http://stackoverflow.com/q/12671041/1211524

Is it time to turn on the type based optimizations by default?

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Enables type optimizations by default. Fixes #812.

Based off of the discussion at https://groups.google.com/forum/#!topic/closure-compiler-discuss/JPzrMiD_6dk

Question: Should we have a temporary warning or banner for the compiler when this would take effect?

I plan to update the FAQ and any other documentation pieces about this. There are also a few stackoverflow posts I'll edit. Someone should probably change the web service options to match as well (after release).

### CODE REVIEW

**Comment by MatrixFrog** [comment]
Can we change the default value of the flag without changing the name? I think it would be clearer.

**Comment by ChadKillingsworth** [comment]
I thought of that, but there were several issues:

* Most people use the binary flags only for the true state. For instance, I've never seen someone do this:

        --debug false

* I was also trying to make it clearer that this was a significant change and thought that changing the default value of the flag would hide the change too much.

**Comment by ChadKillingsworth** [comment]
Oh and the very name of the flag infers that it is opt-in rather than opt-out.

**Comment by dimvar** [comment]
It is a common convention for a flag's name to describe what it does and then we have on and off states. As such, I agree with Tyler that the current name is more appropriate than disable_type_optimizations.

To avoid hiding the change, we can announce it at the appropriate lists/forums.

**Comment by ChadKillingsworth** [comment]
I can make that change, but it will be the only boolean flag that is on by default.

**Comment by ChadKillingsworth** [comment]
Nevermind - I don't think boolean flags can be disabled like that with args4j. http://args4j.kohsuke.org/args4j/apidocs/org/kohsuke/args4j/Option.html

None of the following worked:

    --use_types_for_optimization false
    --use_types_for_optimization=false
    --use_types_for_optimization=0

**Comment by MatrixFrog** [comment]
Well that's annoying :|

Okay, I guess changing the name makes sense then.

**Comment by ChadKillingsworth** [comment]
Reverted to the original option name and it is now on by default.

**Comment by dimvar** [comment]
lgtm once the travis build is done

**Comment by MatrixFrog** [comment]
lgtm

**Pull request merged**
