### PR TITLE
Annotate some constant properties as @const

### PR DESCRIPTION
**Pull request by realityforge**

### CODE REVIEW

**Comment by brad4d** [comment]
Created internal issue http://b/130161859

**Comment by brad4d** [comment]
imported and sent for testing

**Comment by brad4d** [comment]
testing looks good
sent to @blickly for internal review

**Comment by brad4d** [comment]
re: conflicts mentioned in the status of this PR

I've already resolved them in my internal version.

@realityforge I can push my changes back to you if you want, but I don't think there's much benefit in it.

I expect to get this submitted internally by sometime tomorrow with the push to GitHub coming the next day.

**Comment by realityforge** [comment]
No need to push changes back - we have fixed it in a local integration branch aswell. I had not noticed the PR was in conflict.. But thanks for asking!

**Comment by realityforge** [comment]
Thanks

**Pull request closed without merging**
