### PR TITLE
Fix HTMLVideoElement.prototype.{width,height} type

### PR DESCRIPTION
**Pull request by fredj**
See https://www.w3.org/TR/html5/embedded-content-0.html#the-video-element

---
This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1664)

### CODE REVIEW

**Comment by Dominator008** [comment]
This *might* require an internal cleanup at Google in case people are relying on the wrong types.

**Comment by Dominator008** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/closure-compiler/1664)*

**Comment by dimvar** [comment]
@MatrixFrog I'm trying this out internally. I'm reassigning the PR to me.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/91014522e98ffea3ba6133da7c11c240267fb99c

**Pull request closed without merging**
