### PR TITLE
Add missing 'paramSerializer' in angular.$http.Config

### PR DESCRIPTION
**Pull request by fredj**
See https://docs.angularjs.org/api/ng/service/$http

---
This change is [Reviewable](https://reviewable.io/reviews/google/closure-compiler/1850)

### CODE REVIEW

**Comment by Dominator008** [comment]
@mprobst Can you LGTM this? Thanks!

**Comment by mprobst** [comment]
LGTM.

**Comment by Dominator008** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/closure-compiler/1850)*

**Comment by MatrixFrog** [comment]
Sorry for the delay; this is conflicting with a large change that was made internally which hasn't been pushed to github yet. I'll see if we can get MOE-synced today and then we should be able to bring this in.

**Pull request closed without merging**
