### PR TITLE
Add missing reportValidity externs

### PR DESCRIPTION
**Pull request by nicks**

### CODE REVIEW

**Comment by MatrixFrog** [comment]
no externs for this inside Google so it should be safe to merge this. LGTM once Travis finishes.

**Comment by nicks** [comment]
SNAPSHOT: Failed to read artifact descriptor for com.google.guava:guava:jar:19.0-SNAPSHOT: Could not transfer artifact com.google.guava:guava:pom:19.0-SNAPSHOT

i don't think the failure is related to my change?

**Comment by ChadKillingsworth** [comment]
It's not - @blickly reverted (#1334) Michael's fixes (#1327) for this error to get MOE back in sync. @MatrixFrog is working on it.

**Comment by ChadKillingsworth** [comment]
:+1: Travis is broken, but the tests all passed locally.

**Pull request merged**
