### PR TITLE
Support TypeScript bounded generic types notation

### PR DESCRIPTION
**Pull request by ikabirov**
fix for https://github.com/google/closure-compiler/issues/3410

### CODE REVIEW

**Comment by blickly** [comment]
Created internal issue http://b/134787937

**Comment by blickly** [comment]
I think that the idea of creating a new type syntax that is ignored when type-checking is somewhat dangerous, in that folks using type-checking might get the impression that it's checking something that it isn't. Secondarily, changes like these can make it more difficult to land the full feature (real bounded generics) if people who were using the syntax have created code patterns that don't actually typecheck.

@shicks, do you have any other opinion on adding support for the syntax of TS-style bounded generics (See https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#template) in advance of actually supporting bounded generics in the type system?

**Comment by brad4d** [comment]
Assigned to @shicks to get an answer to the question asked by @blickly above

**Comment by shicks** [comment]
I agree that we don't want to support the syntax until the semantics are also supported, for the same reason we don't want folks using type annotations that aren't actually checked - once they become checked, they're probably going to be wrong.  This is the reason Closure Templates had to invent a whole new syntax for their types when the time came, since too many folks were writing unchecked comments in the "first choice" format.

**Comment by blickly** [comment]
OK, I think we're in agreement that we shouldn't add syntax only for this without type-system support.  @ikabirov, thanks for starting the discussion and sorry we didn't decide to merge the syntax-only support.

**Pull request closed without merging**
